### ISSUE TITLE
This is awesome! Can't get it to work though?

### ISSUE THREAD

**Issue by joshmu** [rmcdaniel/angular-codeigniter-seed#1]
Hey there!

I really like the idea of this as I was looking for a way on combining codeigniter with angularjs and using json web tokens!

When I place the repo files in `public_html` the angular app itself seems to work but when I make requests to the server I get a 404 message.  Would you be able to point me in the right direction to get the calls to codeigniter working?

**Comment by rmcdaniel** [comment]
Closed. Contact me if you still need help. Thanks!
