### ISSUE TITLE
about jwt duration

### ISSUE THREAD

**Issue by skobeo** [rmcdaniel/angular-codeigniter-seed#10]
hi,
just a question about JWT. Context is an angular webapp (in Ionic for example) and a CI API server.
is it safe to never expires the token ? What are best practices ?
Thanks

**Comment by sajwal** [comment]
I think it is not an issue in not expire the token...I myself use it in one of my app to let the user always be logged in ... I provide logout option to flush the token.  However if you want to stop access to only sensitive area of your app you can pass some information along with the token to restrict the content further.... like : group_id , is_allowed  etc.

**Comment by rohit10029** [comment]
is there is way to put time limit on jwt token ?and how to flush the token when log out.

**Comment by paulobitfranca** [comment]
Hi, sorry my english, but let's go...

I made a modification at code to add expiration resource. You can see it:
http://pastebin.com/V21VaDsS

How create the token:
$expiration = strtotime('2017-03-09 11:00:00');
$fields = array();
$fields['login'] = 'paulo@gmail';
$fields['nome_banco'] = 'locadora';
$token = JWT::encode($fields, 'mysecret', $expiration);

I hope it help. If the author likes my idea, put it at the original code...
