### ISSUE TITLE
upgrading the CI

### ISSUE THREAD

**Issue by maev-shadowsong** [rmcdaniel/angular-codeigniter-seed#12]
hi there,

its already aug 2018, would you like to update the codeigniter into latest version?
it seems so many of developers that might look for the update as well
thanks in advance

best regards

**Comment by kennyendowed** [comment]
i agree with @maev-shadowsong and again when am login am go back to login or register page am able to which is not suppose to be pls review it thank your boss

> hi there,
> 
> its already aug 2018, would you like to update the codeigniter into latest version?
> it seems so many of developers that might look for the update as well
> thanks in advance
> 
> best regards

**Comment by rmcdaniel** [comment]
Use Laravel. 😂
