### ISSUE TITLE
How to find Database?

### ISSUE THREAD

**Issue by jitendra-khatri** [rmcdaniel/angular-codeigniter-seed#4]
Firstly Thank you very much for sharing this.

Could you please let me know where I can find Database for running application properly.

**Comment by rmcdaniel** [comment]
You can set your database settings like a typical CodeIgniter 2 application in this file -> https://github.com/rmcdaniel/angular-codeigniter-seed/blob/master/api/application/config/database.php

If you run the command "php api/index.php cli install" it will create the necessary tables for you.

**Comment by vetrivivek** [comment]
sholud i install cli for creating database?

**Comment by ragavanrandy** [comment]
what is the table structure of **acl** and **users** tables in **acs** database for verify this seed project. 
help me please.
